# Generated by Django 4.2 on 2023-04-08 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TodoApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='dueday',
        ),
    ]
