# Generated by Django 4.2 on 2023-04-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoApp', '0002_remove_list_dueday'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='do',
            field=models.BooleanField(default=False),
        ),
    ]
