# Generated by Django 4.2 on 2023-04-08 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TodoApp', '0003_list_do'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='do',
            new_name='done',
        ),
    ]
