# Generated by Django 4.2 on 2023-04-08 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TodoApp', '0004_rename_do_list_done'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='List',
            new_name='Todo',
        ),
    ]
